### ISSUE TITLE
Set also filetime, if available

### ISSUE THREAD

**Issue by pke** [bradenhilton/yt-dlp-FixupMtime#1]
Thanks for writing this, I was just thinking how to unify all the files timestamps.

I am using `(release_timestamp>%Y-%m-%dT%H.%M.%S,upload_timestamp>%Y-%m-%dT%H.%M.%S,timestamp>%Y-%m-%dT%H.%M.%S,epoch>%Y-%m-%dT%H.%M.%S)s` for my output template and it seems the video download also sets mtime to a timestamp if possible, since it contains the time (of the tweet in my case).
It would be nice if this plugin could either use the output files timestamp as a lead or allow a similar pattern to specify the key(s) for using as mtime.

**Comment by bradenhilton** [comment]
Could you provide an example of what happens currently, and what you would like to happen instead?

**Comment by pke** [comment]
Currently trying `--use-postprocessor FixupMtime:mtime_key=release_timestamp` which errors with "expected string or bytes-like object".

Maybe something like `--use-postprocessor FixupMtime:mtime_key=%(release_timestamp,upload_timestamp,upload_date)s`

**Comment by bradenhilton** [comment]
Could you provide a link and sample config that I can use to test?

**Comment by pke** [comment]
```
# Config
-o '%(release_timestamp>%Y,upload_timestamp>%Y,timestamp>%Y,epoch>%Y)s/%(release_timestamp>%Y-%m-%dT%H.%M.%S,upload_timestamp>%Y-%m-%dT%H.%M.%S,timestamp>%Y-%m-%dT%H.%M.%S,epoch>%Y-%m-%dT%H.%M.%S)s-%(title).100s-%(extractor)s-%(id)s-%(resolution)s%(fps&@|)d-%(duration>%Hh%Mm%Ss)s.%(ext)s'
--embed-subs
--windows-filenames
--write-comments
--write-description
--write-subs
--write-auto-subs
--sub-langs all
--extractor-args youtube:max-comments=100,all,100
--parse-metadata "%(release_year,upload_date).4s:(?P<meta_date>.+)"
--use-postprocessor FixupMtime:mtime_key=upload_date
--embed-metadata
--embed-thumbnail
--embed-chapters
--embed-info-json
--write-info-json
--xattrs
```

Link: `https://twitter.com/eddie_1412/status/1633452798363705345`
