### ISSUE TITLE
Feature Request: Change file creation time and not only modified time

### ISSUE THREAD

**Issue by Cabbasca** [bradenhilton/yt-dlp-FixupMtime#7]

**Comment by bradenhilton** [comment]
Creation time isn't recorded on all platforms/filesystems.

Even on supported platforms/filesystems, changing it currently requires hacky workarounds such as changing the system time.

I would instead recommend using a simple script in `exec` that applies the mtime to the creation time **after `FixupMtime` has run**.

On Windows, you can do this trivially with PowerShell:

`Set-CreationTime.ps1`:

```text
param (
    [string]$filePath
)

if (-not (Test-Path -LiteralPath $filePath)) {
    Write-Error "File not found: $filePath"
    exit 1
}

Get-Item -LiteralPath $filePath | ForEach-Object { $_.CreationTime = $_.LastWriteTime }
```

```console
yt-dlp --exec "powershell -File `"path/to/Set-CreationTime.ps1`" {}" -- <URL>
```

(the above command works when yt-dlp is invoked via PowerShell, you might need to experiment with the quoting if yt-dlp is invoked via `cmd.exe`)

If an official/non-hacky way of modifying creation time is added to Python in the future, I'll reconsider, but for now I don't feel like implementing this.
