### ISSUE TITLE
[bug] all downloaded videos have the same hour? (00:00hs)

### ISSUE THREAD

**Issue by throwaway26425** [bradenhilton/yt-dlp-FixupMtime#8]
hi, i'm using: `--use-postprocessor FixupMtime:mtime_key=upload_date`

but, it seems like all videos are being downloaded with the same hour? (00:00hs)

is there a way to fix that?

**Comment by bradenhilton** [comment]
You haven't given enough information.

What link demonstrates the issue?

For that link, what is the value of `upload_date`?

What is the output from the postprocessor?

**Comment by throwaway26425** [comment]
sorry, here's an example: https://www.youtube.com/watch?v=gvdf5n-zI14

`[FixupMtime] Setting mtime of files to `upload_date` (2010-01-12T00:00:00)`

**Comment by bradenhilton** [comment]
`upload_date` is commonly formatted as `YYYYMMDD`. In this format, there is no time information, so the time is not populated:

```console
❯ yt-dlp -j -- https://www.youtube.com/watch?v=gvdf5n-zI14
... "upload_date": "20100112" ...
```

I recommend combining multiple `FixupMtime`s as outlined in the README:

https://github.com/bradenhilton/yt-dlp-FixupMtime/blob/c35cdeac6d1936156d0ac45351119a3786d68e38/README.md#L55-L62

**Comment by throwaway26425** [comment]
hey, it seems to work if I use this:

`--use-postprocessor FixupMtime:mtime_key=timestamp`

here's the output now:

`[FixupMtime] Setting mtime of files to 'timestamp' (2010-01-12T06:50:33+00:00)`

just something weird, on my laptop the file has 3 hours less than the original output (`3:50hs` instead of `6:50hs`).

is this normal?

**Comment by bradenhilton** [comment]
`timestamp` is a UNIX timestamp (number of seconds since `1970-01-01 00:00:00 UTC`. The timestamp itself has no time zone information, which effectively makes it UTC.

Is your time zone UTC-3?

**Comment by throwaway26425** [comment]
> Is your time zone UTC-3?

yes.

what should I do?

**Comment by bradenhilton** [comment]
> if the output says that the video was uploaded at `6:50hs`, then it means that it was originally uploaded at `3:50hs` on my timezone?

That is correct.
